---
name: build-dev-image
on: [workflow_dispatch, push]
jobs:
  build-dev-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build dev image
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: olcf/greggd/dev-image
          tag_with_ref: true
          context: build/
