---
name: build
on: [push]
jobs:
  build-binary:
    runs-on: ubuntu-20.04
    container: ghcr.io/olcf/greggd/dev-image:8.3_20210513
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: greggd
          path: greggd
