---
name: build
on: [push]
jobs:
  build-binary:
    runs-on: ubuntu-20.04
    container: ghcr.io/olcf/greggd/dev-image:8.3_20210513
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Build
        run: go build -v ./cmd/greggd/
      - name: Test
        run: go test -v ./...
      - name: Save artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: greggd
          path: greggd
