---
name: build-dev-image
on: [workflow_dispatch]
jobs:
  build-dev-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Build dev image
        uses: docker/build-push-action@v6
        with:
          context: build/
          pull: true
          push: true
          tags: ghcr.io/olcf/greggd/dev-image:8.3_20210513
