---
name: build-dev-image
on: [workflow_dispatch]
jobs:
  build-dev-image:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: ppc64le
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Build dev image
        uses: docker/build-push-action@v2
        with:
          context: build/
          pull: true
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: ghcr.io/olcf/greggd/dev-image:8.3_20210706-${{ matrix.arch }}
