---
name: build
on: [push]
jobs:
  build-binary:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: amd64
            image: ghcr.io/olcf/greggd/dev-image:8.3_20210706
          - arch: ppc64le
            image: ghcr.io/olcf/greggd/dev-image:8.3_20210706
    container: ghcr.io/olcf/greggd/dev-image:8.3_20210513
    steps:
      - run: |
          docker run --rm --privileged \
          multiarch/qemu-user-static:register --reset
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker run --rm --platform ${{ matrix.arch }} \
          --workdir  "${GITHUB_WORKSPACE}" \
          -v "${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE}" \
          ${{ matrix.image }} \
          "uname -a && make build"
      - name: Test
        run: |
          docker run --rm --platform ${{ matrix.arch }} \
          --workdir  "${GITHUB_WORKSPACE}" \
          -v "${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE}" \
          ${{ matrix.image }} "make test"
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: greggd.${{ matrix.arch }}
          path: greggd
