---
name: build
on: [push]
jobs:
  build-binary:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: amd64
            image: docker://ghcr.io/olcf/greggd/dev-image:8.3_20210706
          - arch: ppc64le
            image: docker://ghcr.io/olcf/greggd/dev-image:8.3_20210706
    container: ghcr.io/olcf/greggd/dev-image:8.3_20210513
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.arch }}
        uses: ${{ matrix.image }}
        with:
          args: 'uname -a && make build'
      - name: Test
        env:
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.arch }}
        uses: docker://${{ matrix.image }}
        with:
          args: make test
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: greggd.${{ matrix.arch }}
          path: greggd
