---
name: release
on: {push: {tags: ['v*.*.*']}}
jobs:
  release:
    runs-on: ubuntu-20.04
    container: ghcr.io/olcf/greggd/dev-image:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export release vars
        id: vars
        shell: bash
        run: |
          echo "::set-output name=version::$(git describe --tags --abbrev=0)"
          echo "::set-output name=release::$(git rev-parse --short HEAD)"
      - name: Build
        run: go build -v ./cmd/greggd/
      - name: Test
        run: go test -v ./...
      - name: Build RPM
        env:
          VERSION: ${{ steps.vars.outputs.version }}
          RELEASE: ${{ steps.vars.outputs.release }}
        run: |
          cd build
          envsubst < nfpm-template.yaml > nfpm.yaml
          nfpm pkg --packager rpm
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
