---
name: release
on: {push: {tags: ['*.*.*']}}
jobs:
  release:
    runs-on: ubuntu-20.04
    container: ghcr.io/olcf/greggd/dev-image:8.3_20210513
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
        # No shallow clone
        with:
          fetch-depth: 0
      - name: Export release vars
        id: vars
        shell: bash
        run: |
          echo "::set-output name=version::$(git describe --tags --abbrev=0)"
          echo "::set-output name=release::$(git rev-parse --short HEAD)"
      - name: Build
        run: go build -v ./cmd/greggd/
      - name: Test
        run: go test -v ./...
      - name: Build RPM
        env:
          VERSION: ${{ steps.vars.outputs.version }}
          RELEASE: ${{ steps.vars.outputs.release }}
        run: |
          envsubst < build/nfpm-template.yaml > build/nfpm.yaml
          nfpm -f build/nfpm.yaml pkg --packager rpm
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: greggd*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
