---
name: release
on: {push: {tags: ['*.*.*']}}
jobs:
  release:
    runs-on: ubuntu-20.04
    container: ghcr.io/olcf/greggd/dev-image:8.3_20210513
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # No shallow clone
        with:
          fetch-depth: 0
      - name: Build
        run: make test
      - name: Test
        run: make test
      - name: Build RPM
        run: |
          make srpm
          make rpm
          cp ~/rpmbuild/SRPMS/*/greggd*.rpm .
          cp ~/rpmbuild/RPMS/*/greggd*.rpm .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            greggd*.rpm
            greggd*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
